[package]
name = "native_language_task"
version = "0.1.0"
authors = ["Rodrigo Torres"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
clap = "2.33.3"
byteorder = "1"